### ISSUE TITLE
Some issues in configs/mi.json

### ISSUE THREAD

**Issue by RhincodonE** [iamgroot42/mimir#17]
Hi,
I found your project to be helpful to my current paper, but I met some problems when I was trying  python run.py --config configs/mi.json. 

Problems:

1. An error reports split is Nonetype, which can be fixed by adjusting the mi.json as:
    "dataset_member": "the_pile_pile_cc_ngram_13_0.2",
    "dataset_nonmember": "the_pile_pile_cc_ngram_13_0.2",

2. An error reports there is no dataset key, which can be fixed by adding this line to the mi.json:
   "dataset_key": "the_pile",
   
I don't whether my adjustments to mi.json are correct. If it's not, could you please give me some suggestions? If these are correct, I suggest adding some tutorial about config files in the github project.

Thanks,
Ethan

**Comment by zjysteven** [comment]
Same question here. It is unclear how to set the config to run evaluation on different datasets listed in Table 1 of the paper. While I do appreciate and understand all the efforts one has to put into a benchmark (I myself has worked on a benchmark for OOD detection), I also expect much more documentation and maintenance being provided.

**Comment by iamgroot42** [comment]
Thanks for pointing this out, @RhincodonE ! The `specific_source` field should be `"Github_ngram_13_<0.8_truncated"` instead of just `Github`, but the way your workaround is right now will create issues. I have updated the config file with this change now- can you test it out and see if it works for you?

In general for different data sources you would replace the `Github` part here for that particular source, and similarly for n-grams you would replace the '13' or '0.8` with valid values (which you can find in the corresponding HF data [here](https://huggingface.co/datasets/iamgroot42/mimir)).

@zjysteven for different datasets you can simply vary the `Github` part above. Please see [this folder](https://github.com/iamgroot42/mimir/blob/main/scripts/paper_scripts/) for more details
